export const MetricData = [
  {
    stage: "Seed Sale",
    percentage: "7",
    amount: "7,000,000",
    vesting: "7.5% unlock at TGE, vesting in 10 months",
    isHetchoChartDistr: true,
  },
  {
    stage: "Private Sale",
    percentage: "13",
    amount: "13,000,000",
    vesting: "7.5% unlock at TGE, vesting in 10 months",
    isHetchoChartDistr: true,
  },
  {
    stage: "Public Sale (IDO)",
    percentage: "2",
    amount: "2,000,000",
    vesting: "30% unlock at TGE, Vesting in 2 months",
    isHetchoChartDistr: false,
  },
  {
    stage: "Team & Operation",
    percentage: "15",
    amount: "15,000,000",
    vesting: "Full lock 2 months after TGE. Vesting in 730 days",
    isHetchoChartDistr: false,
  },
  {
    stage: "Advisor",
    percentage: "5",
    amount: "5,000,000",
    vesting: "Vesting 730 days",
    isHetchoChartDistr: true,
  },
  {
    stage: "Marketing fund",
    percentage: "7",
    amount: "7,000,000",
    vesting: "5% unlock at TGE. Vesting 730 days",
    isHetchoChartDistr: false,
  },
  {
    stage: "In-game Treasury",
    percentage: "21",
    amount: "21,000,000",
    vesting: "Vesting 730 days",
    isHetchoChartDistr: false,
  },
  {
    stage: "Liquidity",
    percentage: "10",
    amount: "10,000,000",
    vesting: "20% added at 1st week, 80% added in 8 months",
    isHetchoChartDistr: false,
  },
  {
    stage: "Staking & Farming",
    percentage: "20",
    amount: "20,000,000",
    vesting: "Vesting 730 days",
    isHetchoChartDistr: false,
  },
];
